// =========================================================
// LA TERMITIÈRE — Données des secteurs
// Source de vérité unique, utilisée par index.html et service.html
// =========================================================

const SECTORS = {

  sport: {
    id: "sport",
    color: "#E2810D",
    colorDark: "#B4670A",
    logo: "images/logos/maxigym.png",
    name: "Maxi Gym",
    tagline: "Sport & santé",
    letter: "A",
    cardText: "Coaching, rééducation et remise en forme, avec ou sans accompagnement personnalisé.",
    mission: "Notre mission est d'accompagner chaque individu, quel que soit son profil, vers un mieux-être physique et durable. À travers un suivi personnalisé par des coachs professionnels ou en accès libre, nous combinons sport, remise en forme et rééducation pour vous aider à atteindre vos objectifs de santé et de performance.",
    services: [
      { title: "Accompagnement & rééducation sportive", text: "Prise en charge personnalisée par nos deux coachs pour les personnes en phase de rééducation, à la suite d'un accident, d'un incident physique, ou pour soulager des tensions musculaires spécifiques." },
      { title: "Coaching & transformation physique", text: "Séances encadrées par nos coachs professionnels pour atteindre des objectifs esthétiques ou de performance (ventre plat, renforcement musculaire, tonification globale)." },
      { title: "Pratique libre", text: "Formule flexible permettant de s'entraîner en autonomie sans l'assistance d'un coach." },
      { title: "Espace équipements modernes", text: "Accès à deux types d'espaces selon vos préférences et votre budget : zone électronique (machines de pointe) ou zone classique (équipements standards)." },
    ],
    tables: [
      {
        title: "Tarifs",
        columns: ["Formule", "Durée", "Tarif"],
        rows: [
          ["Abonnement avec machine électronique", "1 mois", "15 000 F CFA"],
          ["Abonnement sans machine électronique", "1 mois", "10 000 F CFA"],
          ["Abonnement avec machine électronique", "2 semaines", "7 500 F CFA"],
          ["Abonnement sans machine électronique", "2 semaines", "5 000 F CFA"],
          ["Séance à l'unité avec machines", "1 séance", "1 500 F CFA"],
          ["Séance à l'unité sans machines", "1 séance", "1 000 F CFA"],
        ],
      },
    ],
    cible: "Tout le monde.",
    horaires: "Lundi au samedi de 6h à 10h et de 15h à 22h. Dimanche de 16h à 20h.",
    localisation: "Agoè-Daliko, à 200 m du carrefour Azanglo en allant vers le carrefour Kpogli, ainsi qu'à Kara, EWAOU, en face du Foyer Jean 23.",
    photos: ["salle-de-sport-1.jpg", "salle-de-sport-2.jpg", "salle-de-sport-3.jpg", "salle-de-sport-4.jpg", "salle-de-sport-5.jpg", "salle-de-sport-6.jpg", "salle-de-sport-7.jpg", "salle-de-sport-8.jpg", "salle-de-sport-9.jpg", "salle-de-sport-10.jpg", "salle-de-sport-11.jpg", "salle-de-sport-12.jpg", "salle-de-sport-13.jpg", "salle-de-sport-14.jpg", "salle-de-sport-15.jpg", "salle-de-sport-16.jpg", "salle-de-sport-17.jpg", "salle-de-sport-18.jpg", "salle-de-sport-19.jpg", "salle-de-sport-20.jpg", "salle-de-sport-21.jpg", "salle-de-sport-22.jpg", "salle-de-sport-23.jpg", "salle-de-sport-24.jpg"],
    photosDir: "images/salle-de-sport/photos/",
    heroPhoto: "images/salle-de-sport/photos/gym-accueil.jpg",
    videos: [],
    videosDir: "images/salle-de-sport/videos/",
    whatsapp: "22896094949",
    email: "latermitiere2021@gmail.com",
    processPhoto: "images/watermarks/gym-inscription.jpg",
    procedure: [
      { title: "Inscription & fiche de santé", desc: "Remplissez notre fiche d'inscription et le questionnaire médical d'aptitude sportive à l'accueil." },
      { title: "Choix de la formule", desc: "Sélectionnez l'abonnement qui vous correspond (mensuel, bihebdomadaire ou séance à l'unité, avec ou sans machines)." },
      { title: "Paiement & activation", desc: "Réglez vos frais par Mobile Money ou en espèces pour obtenir instantanément votre accès à la salle." },
      { title: "Bilan & entraînement", desc: "Réalisez un bilan de départ avec l'un de nos coachs et démarrez vos entraînements." },
    ],
    faq: [
      { q: "Faut-il un abonnement pour s'entraîner à Maxi Gym ?", a: "Non, la formule « Pratique libre » permet de s'entraîner sans engagement, à la séance (1 500 F CFA avec machines, 1 000 F CFA sans) ou en abonnement mensuel ou de 2 semaines selon vos besoins." },
      { q: "Un coach est-il obligatoire pour s'entraîner ?", a: "Non. Vous pouvez vous entraîner en autonomie, ou bénéficier d'un accompagnement personnalisé par l'un de nos coachs pour la rééducation ou la transformation physique." },
      { q: "Maxi Gym est-il uniquement à Lomé ?", a: "Non, Maxi Gym est présent à Agoè-Daliko (Lomé) et à Kara (EWAOU, en face du Foyer Jean 23)." },
    ],
  },

  briqueterie: {
    id: "briqueterie",
    color: "#9C5B3C",
    colorDark: "#7A4630",
    logo: null,
    name: "La Briqueterie",
    tagline: "Matériaux de construction",
    letter: "B",
    manager: { name: "Lomé Malam Rassoulou", title: "DS (Directeur Superviseur)", photo: "images/equipe/briqueterie-responsable.jpg" },
    cardText: "Production de briques et location de matériel de chantier, transport inclus sur demande.",
    mission: "Acteur clé de la construction, notre secteur Briqueterie a pour mission de fournir des matériaux de haute qualité pour concrétiser tous vos projets immobiliers. De la production de briques robustes à la location de matériel de chantier professionnel, nous accompagnons professionnels et particuliers avec des solutions clé en main, transport inclus.",
    services: [
      { title: "Production et vente de briques", text: "Fabrication et fourniture d'une large gamme de briques : pleines (murs porteurs, fondations), creuses (cloisons légères, isolation) et hourdis (dalles, planchers), dimensions 10, 12 et 15." },
      { title: "Service logistique & transport sur chantier", text: "Deux options d'achat : retrait direct à l'usine, ou livraison sécurisée jusqu'à votre chantier." },
      { title: "Location de matériel de chantier", text: "Bétonnières pour vos mélanges, meules pour le sciage de précision, motos tricycles et camions pour la manutention et le transport." },
    ],
    tables: [
      {
        title: "Les pleines",
        columns: ["Nom des briques", "Sans transport", "Avec transport"],
        rows: [
          ["Briques de 10 pleines", "300 F CFA", "350 F CFA"],
          ["Briques de 12 pleines", "375 F CFA", "425 F CFA"],
          ["Briques de 15 pleines", "450 F CFA", "500 F CFA"],
        ],
      },
      {
        title: "Les creuses",
        columns: ["Nom des briques", "Sans transport", "Avec transport"],
        rows: [
          ["Briques de 10 creuses", "250 F CFA", "300 F CFA"],
          ["Briques de 12 creuses", "275 F CFA", "325 F CFA"],
          ["Briques de 15 creuses", "350 F CFA", "400 F CFA"],
        ],
      },
      {
        title: "Les hourdis",
        columns: ["Nom des briques", "Sans transport", "Avec transport"],
        rows: [
          ["Hourdis 12", "450 F CFA", "500 F CFA"],
          ["Hourdis 15", "500 F CFA", "550 F CFA"],
        ],
      },
    ],
    cible: "Tout client (particulier) nécessiteux.",
    horaires: "Lundi au vendredi de 6h à 12h et de 14h30 à 17h.",
    localisation: "Agoè-Daliko, à proximité du camp GP et du carrefour Sakplétocopé.",
    photos: ["briqueterie-1.jpg", "briqueterie-2.jpg", "briqueterie-3.jpg", "briqueterie-4.jpg", "briqueterie-5.jpg"],
    photosDir: "images/briqueterie/photos/",
    videos: ["briqueterie-1.mp4", "briqueterie-2.mp4"],
    videosDir: "images/briqueterie/videos/",
    whatsapp: "22878850735",
    email: "latermitiere2021@gmail.com",
    procedure: [
      { title: "Sélection des briques", desc: "Choisissez le type de briques (pleines, creuses, hourdis) et les dimensions requises pour votre chantier." },
      { title: "Calcul du devis avec transport", desc: "Nous évaluons le coût global selon que vous choisissiez l'enlèvement à l'usine ou la livraison directe." },
      { title: "Règlement sécurisé", desc: "Effectuez votre règlement par Mobile Money (T-Money, Flooz) ou en espèces directement à notre secrétariat." },
      { title: "Livraison ou enlèvement", desc: "Vos briques sont livrées directement sur votre chantier ou mises à disposition pour un enlèvement à l'usine." },
    ],
    faq: [
      { q: "Quels types de briques proposez-vous ?", a: "Des briques pleines, creuses et hourdis, en dimensions 10, 12 et 15, adaptées aux murs porteurs, cloisons légères et dalles." },
      { q: "Peut-on louer du matériel de chantier sans acheter de briques ?", a: "Oui, la location de bétonnières, meules, motos tricycles et camions est possible indépendamment de tout achat de briques." },
      { q: "Comment payer ma commande ?", a: "Par Mobile Money (T-Money, Flooz) ou en espèces, directement à notre secrétariat." },
    ],
  },

  garderie: {
    id: "garderie",
    color: "#E2A400",
    colorDark: "#B58300",
    logo: "images/logos/garderie.png",
    name: "La Garderie",
    tagline: "Accueil des tout-petits",
    letter: "C",
    cardText: "Un cadre sécurisé et épanouissant pour les enfants de 6 mois à 5 ans, cantine incluse.",
    mission: "Notre mission est d'offrir un cadre sécurisé et épanouissant pour l'éveil des enfants de 6 mois à 5 ans, tout en offrant aux parents actifs une tranquillité d'esprit totale grâce à nos formules flexibles avec cantine incluse.",
    services: [
      { title: "Garde par inscription (long terme)", text: "Accompagnement continu à l'année avec un suivi régulier de l'enfant, selon trois tranches d'âge (6 mois à 1 an, 1 an à 3 ans, 3 ans à 5 ans)." },
      { title: "Garde sans inscription (occasionnelle)", text: "Accueil journalier à la carte, idéal pour un besoin ponctuel ou imprévu." },
      { title: "Restauration & cantine intégrée", text: "Repas inclus d'office dans toutes les formules, pour une alimentation saine, équilibrée et adaptée aux tout-petits." },
    ],
    tables: [
      {
        title: "Tarifs par inscription",
        columns: ["Tranche d'âge", "Frais journaliers", "Forfait mensuel"],
        rows: [
          ["6 mois à 1 an", "1 500 F CFA/jour", "35 000 F CFA"],
          ["1 an à 3 ans", "1 500 F CFA/jour", "45 000 F CFA"],
          ["3 ans à 5 ans", "1 500 F CFA/jour", "65 000 F CFA"],
        ],
      },
    ],
    note: "Inscription à l'année : 10 000 F CFA. Sans inscription : 2 500 F CFA/jour (garde et cantine incluses).",
    cible: "Les parents et familles actives à la recherche d'une solution de garde de confiance, flexible et sécurisée.",
    horaires: "Lundi au samedi de 6h30 à 20h.",
    localisation: "Amarinta, non loin de la pharmacie Shékina.",
    photos: ["garderie-1.jpg", "garderie-2.jpg", "garderie-3.jpg", "garderie-4.jpg", "garderie-5.jpg", "garderie-6.jpg", "garderie-7.jpg", "garderie-8.jpg", "garderie-9.jpg", "garderie-10.jpg", "garderie-11.jpg", "garderie-12.jpg", "garderie-13.jpg"],
    photosDir: "images/garderie/photos/",
    heroPhoto: "images/garderie/photos/garderie-fete.jpg",
    videos: ["garderie-1.mp4", "garderie-2.mp4", "garderie-3.mp4", "garderie-4.mp4", "garderie-5.mp4", "garderie-6.mp4"],
    videosDir: "images/garderie/videos/",
    whatsapp: "22871518895",
    email: "latermitiere2021@gmail.com",
    procedure: [
      { title: "Visite de la garderie", desc: "Venez découvrir notre cadre sécurisé, nos aires de jeux et nos espaces de repos." },
      { title: "Dossier & formalités", desc: "Constituez le dossier avec le carnet de vaccination de l'enfant, un extrait de naissance et une fiche de contact d'urgence." },
      { title: "Entretien personnalisé", desc: "Échangez avec notre équipe sur le rythme de votre enfant (sommeil, alimentation, caractère)." },
      { title: "Adaptation & accueil", desc: "Planifiez des demi-journées d'adaptation progressive pour intégrer l'enfant en toute sérénité." },
    ],
    faq: [
      { q: "À partir de quel âge la garderie accueille-t-elle les enfants ?", a: "Dès 6 mois et jusqu'à 5 ans, avec un suivi adapté à trois tranches d'âge (6 mois à 1 an, 1 an à 3 ans, 3 ans à 5 ans)." },
      { q: "Peut-on inscrire son enfant seulement pour quelques jours ?", a: "Oui, la formule sans inscription permet une garde occasionnelle à la journée (2 500 F CFA/jour, cantine incluse), sans engagement à l'année." },
      { q: "Que faut-il fournir pour l'inscription ?", a: "Le carnet de vaccination de l'enfant, un extrait de naissance et une fiche de contact d'urgence." },
    ],
  },

  agro: {
    id: "agro",
    color: "#27A64F",
    colorDark: "#1E8440",
    logo: "images/logos/maxiagro.png",
    name: "Maxi Agro",
    tagline: "Élevage et agriculture",
    letter: "D",
    cardText: "Élevage de précision et productions agricoles, en autosuffisance alimentaire totale.",
    mission: "Assurer une production agropastorale autonome et performante. Maxi Agro se donne pour mission d'élever et de fournir au marché des animaux de races sélectionnées et adaptées aux préférences de nos clients. En nous appuyant sur une agriculture interne dédiée à l'alimentation de notre cheptel, nous visons une autosuffisance totale pour garantir la qualité constante de nos élevages, sans dépendance extérieure.",
    services: [
      { title: "Volailles & œufs", text: "Élevage ciblé et vente de races performantes et recherchées (Goliath, Noiler, Isabrown, Leghorn, poulets de chair, canards, dindons, pigeons) et production d'œufs." },
      { title: "Élevage de ruminants", text: "Vente et approvisionnement en ovins/caprins (races Sahélienne, Djallonké, mouton de Vogan) ainsi qu'en bovins (vaches, taureaux, génisses)." },
      { title: "Embouche de béliers", text: "Engraissement optimisé de béliers pour garantir des animaux vigoureux, spécifiquement préparés pour les marchés de fêtes et grands événements." },
      { title: "Logistique de livraison", text: "Service d'expédition sur site réservé exclusivement aux commandes de grande quantité (frais de transport à la charge du client)." },
    ],
    tables: [],
    cible: "Particuliers et ménages, professionnels (restaurateurs, commerçants, bouchers, grossistes), éleveurs et acteurs du secteur.",
    horaires: "Lundi au dimanche de 5h30 à 18h.",
    localisation: "Agbelouvé.",
    photos: ["maxi-agro-1.jpg", "maxi-agro-4.jpg", "maxi-agro-5.jpg", "maxi-agro-6.jpg", "maxi-agro-7.jpg", "maxi-agro-8.jpg", "maxi-agro-9.jpg", "maxi-agro-10.jpg", "maxi-agro-11.jpg", "maxi-agro-12.jpg", "maxi-agro-13.jpg", "maxi-agro-14.jpg", "maxi-agro-15.jpg", "maxi-agro-16.jpg", "maxi-agro-17.jpg"],
    photosDir: "images/maxi-agro/photos/",
    heroPhoto: "images/maxi-agro/photos/agri1.jpeg",
    videos: [],
    videosDir: "images/maxi-agro/videos/",
    whatsapp: "22878850736",
    email: "latermitiere2021@gmail.com",
    processPhoto: "images/watermarks/agro-inscription.jpg",
    procedure: [
      { title: "Sélection des produits", desc: "Consultez notre secrétariat commercial pour connaître les disponibilités des races ou des œufs." },
      { title: "Devis et conditions", desc: "Nous calculons la facture selon les quantités souhaitées (remises professionnelles pour commandes régulières)." },
      { title: "Paiement", desc: "Réglez vos commandes par Mobile Money ou dépôt d'espèces." },
      { title: "Retrait ferme ou livraison", desc: "Venez récupérer vos animaux directement à notre ferme d'Agbelouvé ou demandez notre livraison." },
    ],
    faq: [
      { q: "Vendez-vous uniquement en grande quantité ?", a: "Non, particuliers et ménages peuvent commander de petites quantités ; la livraison sur site est réservée aux commandes de grande quantité." },
      { q: "Quels animaux et produits proposez-vous ?", a: "Volailles et œufs (Goliath, Noiler, Isabrown, Leghorn, canards, dindons, pigeons), ovins/caprins, bovins, ainsi que l'embouche de béliers pour les fêtes et grands événements." },
      { q: "Peut-on venir récupérer sa commande directement à la ferme ?", a: "Oui, à Agbelouvé, ou vous pouvez demander une livraison (frais de transport à votre charge, réservée aux grandes quantités)." },
    ],
  },

  batiment: {
    id: "batiment",
    color: "#2E4A62",
    colorDark: "#1F3446",
    logo: "images/logos/maxibatiment.png",
    name: "Maxi Bâtiment",
    tagline: "BTP",
    letter: "E",
    cardText: "Architecture, génie civil et topographie, du gros œuvre aux finitions.",
    mission: "Promouvoir la construction d'édifices de qualité, durables et historiques. Nous concevons avec précision et bâtissons avec rigueur : notre expertise en génie civil et notre suivi de chantier millimétré garantissent la réussite de vos structures et extensions complexes, dans le respect absolu de vos délais et budgets.",
    services: [
      { title: "Architecture", text: "Conceptions, études, aménagements d'intérieur et d'espaces verts, élaboration budgétaire des projets de construction." },
      { title: "Gros œuvre & second œuvre", text: "Prise en charge complète de vos chantiers résidentiels, commerciaux et administratifs, jusqu'aux finitions sur mesure." },
      { title: "Calculs de structures & études techniques", text: "Dimensionnement des éléments porteurs pour garantir la pérennité de vos ouvrages." },
      { title: "Surélévation & extension", text: "Extension verticale de bâtiments existants, sans compromettre les fondations d'origine." },
      { title: "Réparation", text: "Plomberie, électricité et étanchéité sur les ouvrages existants." },
      { title: "Topographie", text: "Levés de précision, plans visés, sécurisation de terrains." },
      { title: "Vente de briques résistantes", text: "Matériaux robustes pour vos constructions." },
      { title: "Location de matériel BTP", text: "Bétonnière, échafaudage, GPS différentiel, GPS Garmin et station totale, disponibles à la location." },
    ],
    tables: [],
    cible: "Particuliers, administration et ONG.",
    horaires: null,
    localisation: "Lomé, Agoè-Daliko, dans l'immeuble du siège de La Termitière.",
    photos: ["maxi-batiment-1.jpg", "maxi-batiment-2.jpg", "maxi-batiment-3.jpg", "maxi-batiment-4.jpg", "maxi-batiment-5.jpg", "maxi-batiment-6.jpg", "maxi-batiment-7.jpg", "maxi-batiment-8.jpg", "maxi-batiment-9.jpg", "maxi-batiment-10.jpg", "maxi-batiment-11.jpg"],
    photosDir: "images/maxi-batiment/photos/",
    videos: [],
    videosDir: "images/maxi-batiment/videos/",
    whatsapp: "22878850738",
    email: "latermitiere2021@gmail.com",
    procedure: [
      { title: "Étude et brief client", desc: "Prenez rendez-vous avec nos équipes pour présenter vos plans de construction ou exprimer vos besoins en rénovation." },
      { title: "Visite de terrain & devis", desc: "Nous effectuons une visite technique si nécessaire, puis vous remettons une proposition technique et financière." },
      { title: "Signature et contractualisation", desc: "Nous validons ensemble le calendrier d'exécution des travaux." },
      { title: "Exécution & suivi de chantier", desc: "Lancement des travaux, avec suivi d'avancement jusqu'à la remise des clés." },
    ],
    faq: [
      { q: "Prenez-vous en charge un projet du plan à la livraison ?", a: "Oui, de l'architecture et l'étude technique jusqu'au gros œuvre, aux finitions et au suivi de chantier complet." },
      { q: "Faites-vous aussi de la réparation sur des bâtiments existants ?", a: "Oui : plomberie, électricité, étanchéité, ainsi que la surélévation et l'extension de bâtiments existants sans compromettre les fondations." },
      { q: "Travaillez-vous avec les particuliers ou seulement les entreprises ?", a: "Les deux : particuliers, administrations et ONG." },
    ],
  },

  logistique: {
    id: "logistique",
    color: "#0E7C86",
    colorDark: "#0A5F67",
    logo: "images/logos/maxilogistique.png",
    name: "Maxi Logistique",
    tagline: "Prestations événementielles",
    letter: "F",
    cardText: "Installation de tente et espace VIP, décoration, tables et chaises, gazon, sono et animation pour vos événements.",
    comingSoon: false,
    mission: "Maxi Logistique prend en charge l'organisation matérielle de vos événements, de l'installation à l'animation : tentes et espace VIP, décoration, mobilier, gazon synthétique et sonorisation, pour un rendu clé en main à Kara, Sokodé et Lomé.",
    services: [
      { title: "Installation de tente & espace VIP", text: "Montage de tentes de réception et aménagement d'un espace VIP adapté à la taille de votre événement." },
      { title: "Décoration", text: "Décoration complète sur mesure (arches de ballons, nappage, fleurs) pour cérémonies, mariages et événements d'entreprise." },
      { title: "Tables & chaises VIP", text: "Location de tables et de chaises VIP en quantité, avec housses et nappage assortis." },
      { title: "Gazon synthétique", text: "Pose de gazon synthétique pour un espace de réception propre et soigné." },
      { title: "Sono & animation", text: "Sonorisation et animation pour rythmer vos réceptions et cérémonies." },
    ],
    tables: [],
    cible: "Particuliers et entreprises organisant un événement (mariage, cérémonie, réception).",
    horaires: null,
    localisation: "Interventions à Kara, Sokodé et Lomé.",
    photos: ["logistique-accueil.jpg", "maxi-logistique-9.jpg", "maxi-logistique-1.jpg", "maxi-logistique-2.jpg", "maxi-logistique-3.jpg", "maxi-logistique-5.jpg", "maxi-logistique-10.jpg", "maxi-logistique-12.jpg", "maxi-logistique-14.jpg", "maxi-logistique-17.jpg", "maxi-logistique-18.jpg", "maxi-logistique-19.jpg"],
    photosDir: "images/maxi-logistique/photos/",
    heroPhoto: "images/maxi-logistique/photos/maxi-logistique-9.jpg",
    videos: ["maxi-logistique-1.mp4"],
    videosDir: "images/maxi-logistique/videos/",
    whatsapp: "22878850737",
    email: "latermitiere2021@gmail.com",
    faq: [
      { q: "Intervenez-vous seulement à Kara ?", a: "Non, nous intervenons à Kara, Sokodé et Lomé." },
      { q: "Que comprend une prestation clé en main ?", a: "L'installation de la tente et de l'espace VIP, la décoration, les tables et chaises, le gazon synthétique, la sonorisation et l'animation." },
      { q: "Peut-on louer uniquement des chaises et tables, sans décoration ?", a: "Oui, chaque prestation (tente, décoration, mobilier, gazon, sono) peut être demandée séparément selon vos besoins." },
    ],
  },

  efoncier: {
    id: "efoncier",
    color: "#4B4478",
    colorDark: "#332D57",
    logo: null,
    name: "La Foncière",
    tagline: "Sécurisation foncière",
    letter: "G",
    cardText: "Sécurisation et suivi de vos dossiers de terrain au Togo, de l'achat à l'immatriculation, en toute transparence.",
    comingSoon: false,
    mission: "L'achat d'un terrain peut cacher un risque : limites inexistantes, périmètre non défini, géolocalisation absente. La Foncière apprécie votre dossier avant tout engagement et refuse les missions à risque plutôt que d'exposer le client : du terrain coutumier au titre foncier signé, nous prenons votre dossier en main, étape par étape, en toute transparence.",
    services: [
      { title: "Cession / Vente de terrain", text: "Terrain nu, terrain avec levé, ou terrain avec acte notarié." },
      { title: "Immatriculation (titre en cours)", text: "Levé, bornage, puis délivrance du titre." },
      { title: "Achat d'un terrain déjà titré", text: "Vérification du titre existant et mutation à votre nom." },
      { title: "Mutation de nom", text: "Transfert du titre foncier au nom du nouveau propriétaire." },
      { title: "Morcellement d'un titre global", text: "Division d'un titre en plusieurs parcelles distinctes." },
      { title: "Donation", text: "Constitution et sécurisation du dossier de donation d'un terrain." },
      { title: "Reconstitution de dossier d'héritage", text: "Reconstitution des pièces manquantes pour un terrain hérité." },
      { title: "Lotissement", text: "Autorisation du Ministère de l'Urbanisme pour la création d'un lotissement." },
      { title: "Contrat de gestion de surfaces rurales", text: "Gestion et morcellement de surfaces rurales en vue d'une vente en lots." },
    ],
    highlights: [
      { title: "L'appréciation avant mission", text: "7 critères bloquants vérifiés sur le terrain. Si l'un est constaté, la mission est annulée : vous n'avancez jamais dans le vide." },
      { title: "La transparence des coûts", text: "Chaque dossier détaille les frais réellement engagés par nature (honoraires, administratif, transport, notaire, géomètre, taxes OTR…), sur la base de repères officiels." },
      { title: "Le suivi numérique", text: "Tableau de bord, journal des actions, statut de chaque étape (en attente, en cours, validé, rejeté), pièces jointes (titre, plan visé, levé, actes) rattachées au dossier et à la parcelle." },
      { title: "L'écosystème complet", text: "Propriétaires, cédants, acquéreurs, héritiers, notaires, géomètres, conservateurs : tous les acteurs sont tracés dans le dossier." },
      { title: "Conformité & sérieux", text: "Procédures conformes GUF/OTR, bornage contradictoire assermenté par un géomètre, respect du délai d'opposition de 3 mois au Journal Officiel." },
    ],
    tables: [],
    cible: "Particuliers, familles et investisseurs achetant, vendant, héritant ou sécurisant un terrain au Togo.",
    horaires: null,
    localisation: null,
    photos: ["efoncier-1.jpg", "efoncier-2.jpg", "efoncier-3.jpg", "efoncier-4.jpg", "efoncier-5.jpg", "efoncier-6.jpg", "efoncier-7.jpg", "efoncier-8.jpg", "efoncier-9.jpg"],
    photosDir: "images/e-foncier/photos/",
    heroSkip: true,
    videos: [],
    videosDir: "images/e-foncier/videos/",
    whatsapp: "22896094949",
    email: "latermitiere2021@gmail.com",
    procedure: [
      { title: "Collecte des pièces du cédant", desc: "Rassemblement de tous les documents disponibles sur le terrain et son propriétaire." },
      { title: "Appréciation de la base", desc: "Vérification sur 7 critères bloquants : dossier approuvé, annulé, ou accepté sous réserve." },
      { title: "Enquête terrain", desc: "Vérification physique de la parcelle et de son environnement." },
      { title: "Acte de vente", desc: "Rédaction et signature de l'acte devant notaire." },
      { title: "Bornage", desc: "Bornage contradictoire assermenté par un géomètre agréé." },
      { title: "Immatriculation", desc: "Enregistrement du titre auprès du Conservateur foncier." },
      { title: "Remise du titre", desc: "Remise du titre foncier signé à l'acquéreur." },
    ],
    faq: [
      { q: "Que se passe-t-il si mon terrain présente un risque ?", a: "Nous refusons la mission plutôt que de vous exposer : si l'un des 7 critères bloquants est constaté lors de l'appréciation, le dossier est annulé avant tout engagement." },
      { q: "Combien de temps faut-il pour immatriculer un terrain ?", a: "Le délai dépend du dossier, mais chaque étape (levé, bornage, immatriculation) est suivie avec un statut clair, et un délai d'opposition légal de 3 mois au Journal Officiel s'applique avant la délivrance du titre." },
      { q: "Puis-je suivre l'avancement de mon dossier ?", a: "Oui, un tableau de bord numérique vous donne le statut de chaque étape (en attente, en cours, validé, rejeté) ainsi que les pièces jointes rattachées à votre dossier." },
    ],
  },

  cosmetique: {
    id: "cosmetique",
    color: "#C2467D",
    colorDark: "#9A3563",
    logo: null,
    name: "Maxi Cosmétique",
    tagline: "Beauté & cosmétiques",
    letter: "H",
    cardText: "Produits de beauté et de soin pour hommes, femmes et enfants, du milieu de gamme au haut de gamme, avec conseil et livraison.",
    comingSoon: false,
    mission: "Maxi Cosmétique propose des produits de beauté et de soin pour hommes, femmes et enfants : marques européennes, américaines et locales, dans des gammes accessibles, moyennes et haut de gamme. Une marque propre à La Termitière est en préparation. Conseil beauté et service après-vente accompagnent chaque achat, en boutique ou en livraison.",
    services: [
      { title: "Gammes accessible, moyenne et haut de gamme", text: "Un choix de produits adapté à tous les budgets, du plus accessible au plus luxueux." },
      { title: "Conseil beauté", text: "Une équipe qui vous oriente vers les produits adaptés à votre peau, vos cheveux ou vos besoins." },
      { title: "Service après-vente", text: "Un accompagnement après l'achat en cas de question ou de besoin d'échange." },
      { title: "Livraison nationale & internationale", text: "Vos commandes livrées partout au Togo et à l'international." },
    ],
    tables: [],
    cible: "Hommes, femmes et enfants à la recherche de produits de beauté et de soin, du milieu de gamme au haut de gamme.",
    horaires: "Lundi à vendredi de 7h à 21h30. Samedi de 8h à 22h.",
    localisation: "Agoè (carrefour Tazo) et Amarinta, à 300 m de la pharmacie Shékina en allant vers Sanguéra, à côté de la Garderie La Termitière.",
    photos: ["maxi-cosmetique-1.jpg", "maxi-cosmetique-2.jpg", "maxi-cosmetique-3.jpg", "maxi-cosmetique-4.jpg", "maxi-cosmetique-5.jpg", "maxi-cosmetique-6.jpg", "maxi-cosmetique-7.jpg", "maxi-cosmetique-8.jpg", "maxi-cosmetique-9.jpg", "maxi-cosmetique-10.jpg"],
    photosDir: "images/maxi-cosmetique/photos/",
    heroPhoto: "images/maxi-cosmetique/photos/maxi-cosmetique-2.jpg",
    videos: [],
    videosDir: "images/maxi-cosmetique/videos/",
    whatsapp: "22897056547",
    email: "latermitiere2021@gmail.com",
    tiktok: "https://www.tiktok.com/search?q=MaxiCosmetique1%262",
    tiktokLabel: "MaxiCosmetique1&2",
    faq: [
      { q: "Quelles marques trouve-t-on chez Maxi Cosmétique ?", a: "Des marques européennes, américaines et locales, dans des gammes accessibles, moyennes et haut de gamme. Une marque propre à La Termitière est également en préparation." },
      { q: "Livrez-vous en dehors du Togo ?", a: "Oui, la livraison est possible partout au Togo ainsi qu'à l'international." },
      { q: "Quels sont vos horaires d'ouverture ?", a: "Du lundi au vendredi de 7h à 21h30, et le samedi de 8h à 22h." },
    ],
  },

};

const SECTOR_ORDER = ["sport", "briqueterie", "garderie", "agro", "batiment", "logistique", "efoncier", "cosmetique"];

if (typeof module !== "undefined") {
  module.exports = { SECTORS, SECTOR_ORDER };
}
